### ISSUE TITLE
User header showing "Welcome Anonymous" even if connected right

### ISSUE THREAD

**Issue by tedr56** [psychobunny/nodebb-theme-pewter#1]
I have admin access and all, but the header show me as Anonymous.

All right in ACP

**Comment by psychobunny** [comment]
Hey thanks @tedr56 - I fixed this last night at 98f0e0056526bbd6a3bdd80aa92364fe2bfe917c but forgot to publish the update to npm. Let me make a few more tweaks and I'll publish soon :)

**Comment by psychobunny** [comment]
published 0.0.2 please `npm update` :)
